### ISSUE TITLE
Parte 1: UX.

### ISSUE THREAD

**Issue by RaquelCC** [RaquelCC/scl-2018-12-bc-core-data-lovers#1]
Definir el usuario a través de un formulario que subiremos a un foro de LoL, para determinar el uso especifico de la pagina.

- [x] Redactar formulario.

- [x]  Subir formulario al foro.

- [x] Filtrar respuestas de datos de usuario

- [x]  Crear historias de usuario.

- [x]  Redefinir prototipo de baja fidelidad.

- [x]  Testear Prototipo.

**Comment by puliv** [comment]
Falta terminar prototipo y testear para rediseñar.

**Comment by RaquelCC** [comment]
Investigar y definir contenido.

- [x] Investigar sobre sanciones en LoL y acciones que se pueden tomar para denunciar. (Pulié y Raquel)

- [x] Decidir contenido que se mostrará al usuario en la sección de "Sanciones y denuncias". (Pulié)

- [x] Buscar nombre para la sección de "sanciones y denuncias".

- [x] Buscar información sobre early - mid - late game para definir calculo agregado. (Raquel)

- [x] Decidir como vamos a delimitar los tiempos de early game - mid game - late game. (Raquel)

**Comment by RaquelCC** [comment]
Todo listo :D
